[tasks.build]
command = "yarn"
args = ["parcel", "build", "./index.html", "--dist-dir", "../dist"]


[tasks.release]
command = "yarn"
args = ["parcel", "build", "./index.html", "--dist-dir", "../dist"]
