user: "steam"
group: "steam"
targets:
  ubuntu-16.04:
dependencies:
  - memcached
  - curl
  - git
  - build-essential
  - autoconf
  - lib32gcc1
  - bison
  - libssl-dev
  - libyaml-dev
  - libreadline6-dev
  - zlib1g-dev
  - libncurses5-dev
  - libffi-dev
  - libgdbm3
  - libgdbm-dev
services:
  - memcached