nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.6.1.cjs


packageExtensions:
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "^2.2.1"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "^2.2.1"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "^2.2.1"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "^2.2.1"
  "tailwindcss@*":
    dependencies:
      "postcss": "^8.*"
  "postcss-modules@*":
    dependencies:
      "postcss": "^8.*"
