services:
  client:
    build:
      dockerfile: ./Dockerfile.client
      context: .
    image: registry.hub.docker.com/mbround18/ark-manager-client:latest
    entrypoint: ["/bin/sh"]

  instance:
    build: .
    image: registry.hub.docker.com/mbround18/ark-manager-web:latest
    depends_on:
      - "client"
    volumes:
      - "./tmp/game:/home/steam/ARK"
      - "./tmp/steam:/home/steam/steamcmd"
    ports:
      - "8080:8080"
      - "27016:27016"
      - "7778:7778"
      - "32330:32330"
