FROM registry.hub.docker.com/library/node:lts as ClientBuild
WORKDIR /apps/client
COPY ./client/package.json ./yarn.lock ./.yarnrc.yml ./
COPY ./.yarn/releases ./.yarn/releases
RUN yarn install
COPY ./client  ./
RUN NODE_ENV=production OUT_DIR=/apps/client/build yarn workspace client build


FROM registry.hub.docker.com/library/caddy:latest
COPY --from=ClientBuild /apps/client/build /apps/client
COPY ./config/Caddyfile /etc/caddy/Caddyfile
