services:
  client:
    build:
      dockerfile: ./Dockerfile.client
      context: .
    image: mbround18/ark-manager-client:latest
    platform: linux/amd64
    pull_policy: if-not-present
    entrypoint: ["/bin/sh"]

  instance:
    build: .
    image: mbround18/ark-manager-web:rebuild
    pull_policy: if-not-present
    platform: linux/amd64
    depends_on:
      - "client"
    volumes:
      - "./tmp/game:/home/steam/ARK"
      - "./tmp/steam:/home/steam/steamcmd"
    ports:
      - "8080:8080"
      - "27016:27016"
      - "7778:7778"
      - "32330:32330"
