[tasks.format]
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]


[tasks.yew-serve]
workspace = false
command = "yarn"
args = ["workspace", "client", "dev"]

[tasks.server-serve]
workspace = false
command = "cargo"
args = ["run"]

[tasks.rocket-serve]
workspace = false
run_task = "server-serve"


[tasks.serve]
workspace = false
run_task = { name = ["yew-serve", "server-serve"], parallel = true }
