packages:
  - ./client
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  es5-ext: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  svelte-preprocess: true
minimumReleaseAge: 20160
minimumReleaseAgeExclude:
  - immer@11.1.18
  - "@sveltejs/load-config@0.2.3"
  - postcss@8.5.26
  - svelte-check@4.7.6
  - vite@8.2.1
