apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name | default (.Release.Name) }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Release.Name}}
spec:
  ports:
  {{- range $key, $val := .Values.global.ports }}
    - port: {{$val.port}}
      name: {{$val.name}}
  {{- end }}
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: {{.Release.Name}}
