apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Release.Name}}
  serviceName: {{.Release.Name}}
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: {{.Release.Name}}
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{.Release.Name}}
          image: {{.Values.global.image}}
          imagePullPolicy: Always
          env:
            {{- range $key, $val := .Values.statefulSet.env }}
            - name: {{$val.name}}
              value: {{$val.value}}
            {{- end }}
          ports:
            {{- range $key, $val := .Values.global.ports }}
            - containerPort: {{$val.port}}
              name: {{$val.name}}
            {{- end }}
          volumeMounts:
            - name: {{.Release.Name}}
              subPath: game
              mountPath: /home/steam/ARK
            - name: {{.Release.Name}}
              subPath: steamcmd
              mountPath: /home/steam/steamcmd
            - name: {{.Release.Name}}
              subPath: steam
              mountPath: /home/steam/Steam
  volumeClaimTemplates:
    - metadata:
        name: {{.Release.Name}}
        namespace: {{.Release.Namespace}}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{.Values.storage.className}}
        resources:
          requests:
            storage: {{.Values.storage.size}}
