name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:GH_TOKEN
          access_token: ${{ github.token }}
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: "major,minor,patch,release,documentation,dependencies"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['major','minor','patch', 'documentation']"
          BANNED_LABELS: "banned"
